Rails.application.routes.draw do
  # --- System & Engines ---
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  mount MissionControl::Jobs::Engine, at: "/jobs"

  get "up" => "rails/health#show", as: :rails_health_check

  # --- Authentication ---
  # Generated by authentication-zero
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  resources :sessions, only: [ :index, :show, :destroy ]
  resource  :password, only: [ :edit, :update ]

  namespace :identity do
    resource :email,              only: [ :edit, :update ]
    resource :name,               only: [ :edit, :update ]
    resource :email_verification, only: [ :show, :create ]
    resource :password_reset,     only: [ :new, :edit, :create, :update ]
  end

  namespace :authentications do
    resources :events, only: :index
  end

  # Social Login
  get  "/auth/failure",            to: "sessions/omniauth#failure"
  get  "/auth/:provider/callback", to: "sessions/omniauth#create"
  post "/auth/:provider/callback", to: "sessions/omniauth#create"

  # Admin Masquerade
  post "users/:user_id/masquerade", to: "masquerades#create", as: :user_masquerade

  namespace :sessions do
    resource :passwordless, only: [ :new, :edit, :create ]
    resource :sudo, only: [ :new, :create ]
  end

  # --- Onboarding (Public Access) ---
  # The link users click in their email to join a team
  resource :invitation_acceptance, only: [ :show, :update ]

  # --- App Core (Dashboard) ---
  # The main dashboard is the project list
  root "projects#index"

  resources :projects do
    resources :clips, only: [ :show ] # /projects/1/clips/2
  end

  # This enables the /notifications page
  resources :notifications, only: [ :index, :show ] do
    collection do
      post :mark_all_read
    end
  end

  # --- Team & Workspace Management ---
  # 1. Workspace CRUD & Switching
  resources :accounts, only: [ :new, :create, :edit, :update, :destroy ] do
    member do
      post :switch
    end
  end

  # 2. Default settings
  get "/settings", to: "home#index"

  # 3. Team Directory & Invites
  resources :members, only: [ :index ]      # The directory list
  resources :memberships, only: [ :update, :destroy ] # Removing a user / leaving
  resources :invitations, only: [ :new, :create, :destroy ] do
    member do
      post :resend
    end
  end

  # --- Marketing / Static ---
  get "pricing", to: "static_pages#pricing"
  get "privacy", to: "static_pages#privacy"
  get "support", to: "static_pages#support"
  get "tos",     to: "static_pages#tos"

  # Optional: A dedicated marketing home if user is NOT logged in
  # root "home#index", as: :marketing_root
end
