class AddDetailsToAccounts < ActiveRecord::Migration[8.1]
  def change
    add_column :accounts, :name, :string, null: false, default: "My Workspace"
    add_column :accounts, :public_id, :string, null: false
    # Remove the default index generated by rails and add a UNIQUE one
    remove_index :accounts, :public_id if index_exists?(:accounts, :public_id)
    add_index :accounts, :public_id, unique: true
  end
end
